// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceTruckerCompany.API.Data;

#nullable disable

namespace SpaceTruckerCompany.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Credits")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfShips")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.SpaceShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<int>("MaxCargo")
                        .HasColumnType("int");

                    b.Property<int>("MaxFuel")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpaceShips");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.SpaceShipEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoSpace")
                        .HasColumnType("int");

                    b.Property<double>("CurrentFuel")
                        .HasColumnType("float");

                    b.Property<double>("FuelUsageRate")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int?>("SpaceStationId")
                        .HasColumnType("int");

                    b.Property<int>("UsedCargoSpace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ShipId");

                    b.HasIndex("SpaceStationId");

                    b.ToTable("SpaceShipEntries");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.SpaceShipRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentCoordinatesX")
                        .HasColumnType("float");

                    b.Property<double>("CurrentCoordinatesY")
                        .HasColumnType("float");

                    b.Property<double>("DestinationCoordinatesX")
                        .HasColumnType("float");

                    b.Property<double>("DestinationCoordinatesY")
                        .HasColumnType("float");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpaceShipRoutes");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.SpaceStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CoordinatesX")
                        .HasColumnType("float");

                    b.Property<double>("CoordinatesY")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpaceStations");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.TradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TradeItems");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.TradeItemEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BuyPrice")
                        .HasColumnType("float");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("SellPrice")
                        .HasColumnType("float");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int?>("SpaceShipId")
                        .HasColumnType("int");

                    b.Property<int?>("SpaceStationId")
                        .HasColumnType("int");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShipId");

                    b.HasIndex("SpaceShipId");

                    b.HasIndex("SpaceStationId");

                    b.ToTable("TradeItemEntries");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.SpaceShipEntry", b =>
                {
                    b.HasOne("SpaceTruckerCompany.API.Models.Player", "Owner")
                        .WithMany("Ships")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceTruckerCompany.API.Models.SpaceShip", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceTruckerCompany.API.Models.SpaceStation", null)
                        .WithMany("Ships")
                        .HasForeignKey("SpaceStationId");

                    b.Navigation("Owner");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.TradeItemEntry", b =>
                {
                    b.HasOne("SpaceTruckerCompany.API.Models.TradeItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceTruckerCompany.API.Models.SpaceShipEntry", "Ship")
                        .WithMany("Cargo")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceTruckerCompany.API.Models.SpaceShip", null)
                        .WithMany("TradeItems")
                        .HasForeignKey("SpaceShipId");

                    b.HasOne("SpaceTruckerCompany.API.Models.SpaceStation", null)
                        .WithMany("TradeItems")
                        .HasForeignKey("SpaceStationId");

                    b.Navigation("Item");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.Player", b =>
                {
                    b.Navigation("Ships");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.SpaceShip", b =>
                {
                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.SpaceShipEntry", b =>
                {
                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("SpaceTruckerCompany.API.Models.SpaceStation", b =>
                {
                    b.Navigation("Ships");

                    b.Navigation("TradeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
